apiVersion: apps/v1
kind: Deployment
metadata:
  name: caks
spec:
  replicas: 1
  selector:
    matchLabels:
      name: caks
  template:
    metadata:
      labels:
        name: caks
    spec:
      serviceAccountName: caks
      containers:
        - name: caks
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - caks
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "caks"
